USE MEGALAUDO;
GO
 
/***************** TABLE VEICULO**************/
/* CREATE */
CREATE PROC INCLUIR_SERVICO 
		@NOME VARCHAR(150),
		@DESCRICAO VARCHAR(500),
		@CLIENTE INT,
		@VEICULO INT,
		@VALOR DECIMAL (18,2)

AS 
INSERT INTO SERVICO (NOME, DESCRICAO, ID_CLIENTE, ID_VEICULO, VALOR, DATASERVICO) 
	VALUES (@NOME, @DESCRICAO, @CLIENTE, @VEICULO, @VALOR, GETDATE());

GO

/* UPDATE */  
CREATE PROC ALTERAR_SERVICO 
		@ID INT,
		@NOME VARCHAR(150),
		@DESCRICAO VARCHAR(500),
		@CLIENTE INT,
		@VEICULO INT,
		@VALOR DECIMAL (18,2)
AS 
UPDATE SERVICO SET NOME = @NOME, DESCRICAO = @DESCRICAO, ID_CLIENTE = @CLIENTE,
		ID_VEICULO = @VEICULO, VALOR = @VALOR, DATAALTERACAO = GETDATE()
		 WHERE ID = @ID;
GO

/*DELETE*/
CREATE PROC EXCLUIR_SERVICO
		@ID INT
AS
DELETE FROM SERVICO WHERE ID = @ID;
GO

/*READ*/
CREATE PROC LEITURA_SERVICOS 
AS
SELECT DISTINCT S.DATASERVICO, S.NOME AS SERVICO, S.DESCRICAO,
		 S.VALOR, C.NOME AS CLIENTE 
FROM SERVICO S 
INNER JOIN CLIENTE C ON S.ID_CLIENTE = C.ID 
ORDER BY S.DATASERVICO 

GO 


CREATE PROC LEITURA_SERVICO_VEICULO
		@PLACA AS VARCHAR(10)
AS
SELECT DISTINCT S.DATASERVICO,
		S.NOME AS SERVICO, 
		S.DESCRICAO,
		S.VALOR,
		V.PLACA,
		V.ANOMODELO,
		V.ANOFABRICACAO
FROM SERVICO S
INNER JOIN VEICULO V ON V.ID = S.ID_VEICULO
WHERE V.PLACA = @PLACA
ORDER BY S.DATASERVICO;
GO

CREATE PROC LEITURA_SERVICO_CLIENTE
		@CPF VARCHAR(200)
AS
SELECT DISTINCT  S.DATASERVICO,
		S.NOME AS SERVICO,
		S.DESCRICAO,
		S.VALOR,
		C.NOME AS CLIENTE
FROM SERVICO S 
INNER JOIN CLIENTE C ON C.ID = S.ID_CLIENTE
WHERE C.CPF = @CPF
GO



/*CONSULTAS */
SELECT * FROM MARCA
SELECT * FROM MODELO
SELECT * FROM VEICULO
SELECT * FROM CLIENTE
SELECT * FROM SERVICO
 
/* TESTE PROC SERVIÇOS */ 
EXEC INCLUIR_VEICULO 'GTI-0101', 1,7, 2010,2011;
EXEC INCLUIR_CLIENTE 'JOAO LIMA', '227155XXXXX', '11952154162', 'BP';
EXEC INCLUIR_SERVICO 'MANUTENCAO', 'TROCA DE VELAS',6,3, 200.20 ;

EXEC ALTERAR_SERVICO 3, 'MANUTENCAO EXTRA', ' LIMPEZA DE BICOS INJETORES', 6, 3, 0.00

EXEC LEITURA_SERVICO 'MA', NULL
EXEC LEITURA_SERVICO '', 'JOAO'
EXEC LEITURA_SERVICO 'MA', 'JOAO'
 