
/************TABLE MODELO**************/
/* CREATE */
CREATE PROC INCLUIR_MODELO
		@MARCA INT,
		@NOME VARCHAR(150),
		@DESCRICAO VARCHAR(250)

AS 
INSERT INTO MODELO (ID_MARCA, NOME , DESCRICAO) VALUES (@MARCA ,@NOME, @DESCRICAO);

GO
/* UPDATE */ 
CREATE PROC ALTERAR_MODELO
			@ID INT,
			@MARCA INT,
			@NOME VARCHAR(150),
			@DESCRICAO VARCHAR(250)
AS 
UPDATE MODELO SET ID_MARCA = @MARCA, NOME = @NOME, DESCRICAO = @DESCRICAO WHERE ID = @ID;
GO
/*DELETE*/
CREATE PROC EXCLUIR_MODELO
		@ID INT
AS
DELETE FROM MODELO WHERE ID = @ID;
GO
/*READ*/
CREATE PROC LEITURA_MODELO
	@NOME VARCHAR(150)
AS
SELECT * FROM MODELO WHERE NOME LIKE '%' + @NOME + '%'
GO
 
 
 --DROP PROC ALTERAR_MODELO
 
/*CONSULTAS */ 
SELECT * FROM MODELO
 
/* TESTE PROC MODELO */
EXEC INCLUIR_MODELO 1,'EX', 'EX 1.5 AUTOMATICO'

EXEC INCLUIR_MODELO 1,'EX', NULL /* ERRO, POIS JA EXISTE MODELO CADASTRADO */

EXEC ALTERAR_MODELO 1, 'EX', 'DESCRIÇÃO ALTERADA'

EXEC EXCLUIR_MODELO 'EX'

EXEC LEITURA_MODELO 'E'

 