 
--USE master;
--DROP DATABASE MEGALAUDO;

CREATE DATABASE MEGALAUDO; 
GO 

USE MEGALAUDO;
GO

CREATE TABLE MARCA (
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(150) UNIQUE NOT NULL,
DESCRICAO VARCHAR(250)
)

CREATE TABLE MODELO (
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(20) UNIQUE,
DESCRICAO VARCHAR(200),
ID_MARCA INT NOT NULL
CONSTRAINT FK_MARCA_MODELO FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID)
)

CREATE TABLE VEICULO(
ID INT NOT NULL IDENTITY PRIMARY KEY,
PLACA VARCHAR(7) NOT NULL UNIQUE,
ID_MARCA INT NOT NULL,
ID_MODELO INT NOT NULL,
ANOMODELO INT,
ANOFABRICACAO INT,
CONSTRAINT FK_MARCA_VEICULO FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID),
CONSTRAINT FK_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO (ID)
)
GO

CREATE TABLE CLIENTE(
ID INT IDENTITY NOT NULL PRIMARY KEY,
NOME VARCHAR(240) NOT NULL,
CPF VARCHAR(11) UNIQUE NOT NULL,
TELEFONE VARCHAR(16) NOT NULL,
ENDERECO VARCHAR(250) NOT NULL
)
GO

CREATE TABLE SERVICO (
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(150) NOT NULL,
DESCRICAO VARCHAR(500),
ID_CLIENTE INT NOT NULL,
ID_VEICULO INT NOT NULL,
VALOR DECIMAL (18,2)
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
CONSTRAINT FK_VEICULO FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID)
)
GO

ALTER TABLE SERVICO ADD DATASERVICO DATETIME;
GO
/*
CREATE UNIQUE INDEX MARCA_IDX 
ON MARCA(NOME) 
GO

CREATE UNIQUE INDEX MODELO_IDX
ON MODELO(NOME)
GO

CREATE UNIQUE INDEX VEICULO_IDX
ON VEICULO(PLACA)
GO
*/

ALTER TABLE SERVICO ADD DATAALTERACAO DATETIME;